name = "hexisle"
author = "vcup"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7598129b94cc053ccd43f94cc9d41a9a9ef5877f112ef519c627939a09b6d155"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"

[options]
datapack-folder = "datapacks"
