name = "hexisle"
author = "vcup"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ecb88c4cc50fc59ed39a31e594e47ed3a5dcc0d49ad386133f15c7990ad49baa"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"

[options]
datapack-folder = "datapacks"
